[program:ugc_library]
directory=/root/ugc_library
command=/root/ugc_library/venv/bin/gunicorn --workers 3 --bind unix:/root/ugc_library/phd_library/app.sock phd_library.wsgi:application
autostart=true
autorestart=true
stderr_logfile=/var/log/gunicorn/ugc_library.err.log
stdout_logfile=/var/log/gunicorn/ugc_library.out.log
environment=DJANGO_SETTINGS_MODULE="phd_library.settings"
